---
##########################################
# There is a race condition that can occur in this automation. Here are the steps in which this scenario happens:
# 1) oc new-app creates a deployment config
# 2) the below automation retrieves the deployment config, and then updates the deployment config
# 3) the OpenShift server updates the deployment config on the server side, which renders our automation side copy out of date
# 4) the automation oc updates the deployment, which fails because the it is out of date
#
# To address this scenario, we recursively import this task file (using static: no) in order to force a retry of the entire task list. There is no block retry at this time in ansible.
#
# Long term, we should move this to oc patch which should solve avoid the race condition
##########################################

# Right now this implementation only supports a single route.
- name: Set Route Fact 
  set_fact:
    route: "{{ app.routes[0] }}"

- name: "Set Facts for Update Ports"
  set_fact:
    update_to_service_required: true
  when: route.service is defined

- name: "Get Deployment Config: {{ app.name }}"
  command: >
    {{ openshift.common.client_binary }} get dc {{ app.name }} -n {{ project.name }} -o json
  register: dc_response
  when: update_to_service_required is defined
  tags:
  - connected

- name: Set Fact for DC object
  set_fact:
    dc: "{{ dc_response.stdout | from_json }}"
  when: update_to_service_required is defined

- name: Attempt to Apply New Port Specs to Deployment Config
  set_fact: 
    deployment_config:   "{{ dc | apply_ports_spec_config( app ) }}"
  when: update_to_service_required is defined

- name: Set Fact for Required Deployment Config Updates
  set_fact: 
    update_to_dc_required: true
  when: update_to_service_required is defined and deployment_config != dc

- name: "Use a unique temporary file to store the Deployment Config object"
  command: mktemp
  register: tempfile
  when: update_to_dc_required is defined

- name: "Prepare the object definition for the Deployment Config"
  copy:
    content:  "{{ deployment_config }}"
    dest: "{{ tempfile.stdout }}"
  when: update_to_dc_required is defined    

- block:
   
  - name: "Apply New Deployment Config"
    command: >
      {{ openshift.common.client_binary }} replace dc {{ app.name }} -f {{ tempfile.stdout }} -n {{ project.name }}
    when: update_to_dc_required is defined
    tags:
    - connected
  
  rescue:

  - name: Retry Pause to prevent race conditions on the Deployment Config
    pause: 
      seconds: 2

  - include: configure_networking.yml
    static: no  

- name: "Deployment Config temporary file clean-up"
  file: 
    path: "{{ tempfile.stdout }}"
    state: absent
  when: update_to_dc_required is defined

- name: "Delete Service: {{ app.name }}"
  command: >
    {{ openshift.common.client_binary }} delete service {{ app.name }} -n {{ project.name }}
  when: update_to_dc_required is defined
  tags:
  - connected

- name: "Create new Service with updated Deployment Config: {{ app.name }}"
  command: >
    {{ openshift.common.client_binary }} expose dc {{ app.name }} -n {{ project.name }}
  when: update_to_dc_required is defined
  tags:
  - connected

- name: "Determine If {{ app.name }} Route Exists"
  command: >
     {{ openshift.common.client_binary }} get route {{ app.name }} -n {{ project.name }} -o json
  register: app_name_exists
  failed_when: false
  changed_when: false

- name: "Expose App with default route: {{ app.name }}"
  command: >
    {{ openshift.common.client_binary }} expose service {{ route | create_unsecured_route_options( app.name ) }} -n {{ project.name }}
  when: app_name_exists.rc == 1 and route.route_type is defined and route.route_type == 'default'
  tags:
  - connected

- name: "Expose App with secured route: {{ app.name }}"
  command: >
    {{ openshift.common.client_binary }} create route {{ route | create_secured_route_options( app.name ) }} -n {{ project.name }}
  when: app_name_exists.rc == 1 and route.route_type is defined and route.route_type in ['edge','reencrypt','passthrough']
  tags:
  - connected