---
- name: "Set Basic Persistent Volume Claim Facts"
  set_fact:
    pvc: "{{ persistent_volume_claims_item }}"

- name: Fail for Missing Persistent Volume Claim Parameters
  fail: msg="This role requires persistent_volume_claims.{{ item }} be set and non empty"
  when: pvc.{{ item }} is not defined or pvc.{{ item }} == ''
  with_items:
  - name
  - access_modes
  - storage

- name: "Determine if {{ pvc.name }} Persistent Volume Claim Exists"
  command: >
     {{ openshift.common.client_binary }} get pvc {{ pvc.name }} -n {{ project.name }} -o json
  register: get_pvc_name_result
  failed_when: false
  changed_when: false

- name: "Use a unique temporary file to store the Persistent Volume Claim object"
  command: mktemp
  register: tempfile
  when: get_pvc_name_result.rc != 0

- name: "Prepare the object definition for the Persistent Volume Claim"
  template:
    src: pvc.j2
    dest: "{{ tempfile.stdout }}"
  when: get_pvc_name_result.rc != 0

- name: "Create Persistent Volume Claim"
  command: >
    {{ openshift.common.client_binary }} create -f {{ tempfile.stdout }} -n {{ project.name }}
  when: get_pvc_name_result.rc != 0

- name: "Persistent Volume Claim temporary file clean-up"
  file: path={{ tempfile.stdout }} state=absent  
  when: get_pvc_name_result.rc != 0

