---
- name: "Set Base environment_variables_string"
  set_fact:
    environment_variables_string: '--env '

- name: "Add variable to environment_variables_string"
  set_fact:
    environment_variables_string: "{{ environment_variables_string }}{{ item }}={{ environment_variables[item] }},"
  with_items: '{{ environment_variables.keys() }}'

- name: "Remove Trailing Comma from environment_variables_string"
  set_fact:
    environment_variables_string: "{{ environment_variables_string[:-1] }}"