---
#### Defensive Programming
# https://github.com/openshift/openshift-ansible/blob/master/docs/best_practices_guide.adoc

- name: "Set Basic Project Facts"
  set_fact:
    project_options: ''
    role_bindings_present: false
    apps_present: false
    project: "{{ project_item }}"

- name: Fail for Missing Project Name
  fail: msg="This role requires project.name to be set and non empty"
  when: project.name is not defined or project.name == ''

- name: "Set Imagestream Fact For Build Environment"
  set_fact:
    imagestream_names: []
    build_project_name: "{{ project.name }}"
  when: project.build_environment is defined and project.build_environment == true

- name: "Set Variable role_bindings_present Fact"
  set_fact:
    role_bindings_present: true
  when: project.user_to_role is defined and project.user_to_role != "" and project.user_to_role|length > 0

- name: "Set Variable apps_present Fact"
  set_fact:
    apps_present: true
  when: project.apps is defined and project.apps != "" and project.apps|length > 0

- name: "Add display-name Option"
  set_fact:
    project_options: "{{ project_options }} --display-name='{{ project.display_name }}'"
  when: project.display_name is defined and project.display_name != ''

- name: "Determine If {{ project.name }} Project Exists"
  command: >
     {{ openshift.common.client_binary }} get project {{ project.name }} -o json
  register: project_name_taken
  failed_when: false
  changed_when: false

- name: "Create Project {{ project.name }}"
  when: project_name_taken.rc == 1
  command: >
    {{ openshift.common.client_binary }} new-project {{ project.name }} {{ project_options }}

- include: create_role_binding.yml
  with_items: '{{ project.user_to_role }}'
  loop_control:
    loop_var: role_binding_item
  when: role_bindings_present == true
  static: no

- include: create_app.yml
  with_items: '{{ project.apps }}'
  loop_control:
    loop_var: app_item
  when: apps_present == true
  static: no