---

- include: configure_openshift_cluster.yml
  with_items: '{{ openShift_clusters }}'
  loop_control:
    loop_var: openShift_cluster_item
  when: openShift_clusters is defined and openShift_clusters != "" and openShift_clusters|length > 0

