--- 
  - name: Create IPA user
    ipa_user:
      ipa_admin_user: "{{ ipa_admin_user }}"
      ipa_admin_password: "{{ ipa_admin_password }}"
      givenname: "{{ item.first_name }}"
      sn: "{{ item.last_name }}"
      uid: "{{ item.user_name }}"
      password: "{{ item.user_name }}"
      email: "{{ item.email }}"
    with_items: "{{ users }}"
