---
- name: "Log in to OpenShift Client"
  command: >
    {{ openshift.common.client_binary }} login {{ openshift_host_env }} 
    --insecure-skip-tls-verify=true --username={{ openshift_user }} --password={{ openshift_password }}

- name: "Echo Whoami"
  command: >
    {{ openshift.common.client_binary }} whoami   

- name: "Does Project {{ openshift_project_name }} Exist"
  command: >
    bash -c "{{ openshift.common.client_binary }} get project {{ openshift_project_name }} | egrep -c {{ openshift_project_name }}"
  register: project_name_taken
  failed_when: "'NEVER FAIL' in project_name_taken.stderr"

- name: "Output message if project {{ openshift_project_name }} exists"
  when: project_name_taken.stdout != "0"
  debug: msg="Project name {{ openshift_project_name }} exists"

- name: "Create Project {{ openshift_project_name }} if needed"
  when: project_name_taken.stdout == "0"
  command: >
    {{ openshift.common.client_binary }} new-project {{ openshift_project_name }}
